name: Release
on:
  push:
    branches:
      - master
      - testing
      - develop
      - 'develop/*'


jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-${{ runner.os }}-
            node_modules-
      - name: Setup Node.js
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Execute
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci


  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Load node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          # no restore-keys here, so we only accept this exact version
      - name: Execute
        run: yarn affected:lint --parallel --base=$(git describe --tags --abbrev=0)


  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Load node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          # no restore-keys here, so we only accept this exact version
      - name: Execute
        run: yarn affected:test --parallel --base=$(git describe --tags --abbrev=0)


  release:
    name: Release
    needs: [install, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Load node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          # no restore-keys here, so we only accept this exact version
      - name: Execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
